### ISSUE TITLE
Service pods crashed

### ISSUE THREAD

**Issue by wzy1935** [tsegismont/http-proxy-playground#1]
delivery and order server crashed:

```
$ kubectl get pods
NAME                               READY   STATUS             RESTARTS      AGE
delivery-server-57874b6f85-f9gnc   0/1     CrashLoopBackOff   5 (76s ago)   5m10s
delivery-server-57874b6f85-mkhgs   0/1     CrashLoopBackOff   5 (55s ago)   5m10s
edge-server-6f985c6c85-hb684       1/1     Running            0             5m10s
edge-server-6f985c6c85-rkzk6       1/1     Running            0             5m10s
order-server-68474789f7-2tk8n      0/1     CrashLoopBackOff   5 (51s ago)   5m10s
order-server-68474789f7-rs4lv      0/1     CrashLoopBackOff   5 (57s ago)   5m10s
postgres-server-565c56f5d-jpkhk    1/1     Running            0             5m10s
product-server-587dbcb5cc-d2v4h    1/1     Running            0             5m10s
product-server-587dbcb5cc-pfvqn    1/1     Running            0             5m10s
```

Complete log:

```
$ kubectl logs delivery-server-57874b6f85-f9gnc
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true -Dvertx.disableDnsResolver=true
13:10:25.754 [main] ERROR io.vertx.launcher.application.VertxApplication - Failed in deploying verticle
java.lang.NoClassDefFoundError: com/ongres/scram/common/stringprep/StringPreparation
        at io.vertx.pgclient.impl.codec.InitCommandCodec.handleAuthenticationSasl(InitCommandCodec.java:60) ~[vertx-pg-client-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeAuthentication(PgDecoder.java:381) ~[vertx-pg-client-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:151) ~[vertx-pg-client-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:123) ~[vertx-pg-client-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.ongres.scram.common.stringprep.StringPreparation
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 21 more
io.vertx.launcher.application.impl.CommandException
Usage: VertxApplication [-chw] [-vt] [-cluster-host=<clusterHost>]
                        [-cluster-port=<clusterPort>]
                        [-cluster-public-host=<clusterPublicHost>]
                        [-cluster-public-port=<clusterPublicPort>]
                        [-conf=<configStr>]
                        [-deployment-options=<deploymentOptionsStr>]
                        [-instances=<instances>] [-options=<vertxOptionsStr>]
                        <mainVerticle>
Runs a Vert.x application.
      <mainVerticle>        The main verticle fully qualified class name.
      -options, --options, -vertx-options, --vertx-options=<vertxOptionsStr>
                            Specifies the Vert.x options.
                            It should reference either a JSON file which
                              represents the options OR be a JSON string.
  -c, -cluster, --cluster   If specified, then the Vert.x instance will form a
                              cluster with any other Vert.x instances on the
                              network.
      -cluster-port, --cluster-port=<clusterPort>
                            Port to use for cluster communication.
                            By default, a spare random port is chosen.
      -cluster-host, --cluster-host=<clusterHost>
                            Host to bind to for cluster communication.
                            If this is not specified, Vert.x will attempt to
                              choose one from the available interfaces.
      -cluster-public-port, --cluster-public-port=<clusterPublicPort>
                            Public port to use for cluster communication.
                            By default, Vert.x uses the same as the cluster
                              port.
      -cluster-public-host, --cluster-public-host=<clusterPublicHost>
                            Public host to bind to for cluster communication.
                            By default, Vert.x uses the same as the cluster
                              host.
      -deployment-options, --deployment-options=<deploymentOptionsStr>
                            Specifies the main verticle deployment options.
  -w, -worker, --worker     If specified, then the main verticle is deployed
                              with the worker threading model.
                            Takes precedence over the value defined in
                              deployment options.
      -vt, -virtual-thread, --virtual-thread
                            If specified, then the main verticle is deployed
                              with the virtual thread threading model.
                            Takes precedence over the value defined in
                              deployment options.
      -instances, --instances=<instances>
                            Specifies how many instances of the verticle will
                              be deployed.
                            Takes precedence over the value defined in
                              deployment options.
      -conf, --conf=<configStr>
                            Specifies configuration that should be provided to
                              the verticle.
                            It should reference either a JSON file which
                              represents the options OR be a JSON string.
  -h, -help, --help         Display a help message.
```

**Comment by tsegismont** [comment]
From the root of the project, can you try:

```shell
mvn dependency:tree -pl :http-proxy-playground-order-service
```

It should read this:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -----< com.github.tsegismont:http-proxy-playground-order-service >------
[INFO] Building http-proxy-playground-order-service 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.6.1:tree (default-cli) @ http-proxy-playground-order-service ---
[INFO] com.github.tsegismont:http-proxy-playground-order-service:jar:1.0-SNAPSHOT
[INFO] +- com.github.tsegismont:http-proxy-playground-service-commons:jar:1.0-SNAPSHOT:compile
[INFO] |  +- io.vertx:vertx-web:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  +- io.vertx:vertx-web-common:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  \- io.vertx:vertx-bridge-common:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- io.vertx:vertx-health-check:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- io.vertx:vertx-micrometer-metrics:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  +- io.micrometer:micrometer-core:jar:1.13.0:compile
[INFO] |  |  |  +- io.micrometer:micrometer-commons:jar:1.13.0:compile
[INFO] |  |  |  +- io.micrometer:micrometer-observation:jar:1.13.0:compile
[INFO] |  |  |  \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] |  |  \- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |  +- io.micrometer:micrometer-registry-prometheus:jar:1.11.5:compile
[INFO] |  |  \- io.prometheus:simpleclient_common:jar:0.16.0:compile
[INFO] |  |     \- io.prometheus:simpleclient:jar:0.16.0:compile
[INFO] |  |        +- io.prometheus:simpleclient_tracer_otel:jar:0.16.0:compile
[INFO] |  |        |  \- io.prometheus:simpleclient_tracer_common:jar:0.16.0:compile
[INFO] |  |        \- io.prometheus:simpleclient_tracer_otel_agent:jar:0.16.0:compile
[INFO] |  +- io.vertx:vertx-opentelemetry:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  +- io.opentelemetry:opentelemetry-sdk:jar:1.34.1:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.34.1:compile
[INFO] |  |  |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.34.1:compile
[INFO] |  |  |  |  \- io.opentelemetry:opentelemetry-extension-incubator:jar:1.34.1-alpha:runtime
[INFO] |  |  |  \- io.opentelemetry:opentelemetry-sdk-logs:jar:1.34.1:compile
[INFO] |  |  |     \- io.opentelemetry:opentelemetry-api-events:jar:1.34.1-alpha:runtime
[INFO] |  |  \- io.opentelemetry:opentelemetry-sdk-trace:jar:1.34.1:compile
[INFO] |  +- io.vertx:vertx-launcher-application:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  \- info.picocli:picocli:jar:4.7.4:compile
[INFO] |  +- io.vertx:vertx-service-resolver:jar:5.0.0-SNAPSHOT:compile
[INFO] |  |  \- com.dajudge.kindcontainer:kindcontainer:jar:1.4.3:compile
[INFO] |  |     +- org.testcontainers:testcontainers:jar:1.18.3:compile
[INFO] |  |     |  +- junit:junit:jar:4.13.2:compile
[INFO] |  |     |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  |     |  +- org.slf4j:slf4j-api:jar:2.0.7:compile
[INFO] |  |     |  +- org.apache.commons:commons-compress:jar:1.23.0:compile
[INFO] |  |     |  +- org.rnorth.duct-tape:duct-tape:jar:1.0.8:compile
[INFO] |  |     |  |  \- org.jetbrains:annotations:jar:17.0.0:compile
[INFO] |  |     |  +- com.github.docker-java:docker-java-api:jar:3.3.0:compile
[INFO] |  |     |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.16.1:compile
[INFO] |  |     |  \- com.github.docker-java:docker-java-transport-zerodep:jar:3.3.0:compile
[INFO] |  |     |     +- com.github.docker-java:docker-java-transport:jar:3.3.0:compile
[INFO] |  |     |     \- net.java.dev.jna:jna:jar:5.12.1:compile
[INFO] |  |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.70:runtime
[INFO] |  |        +- org.bouncycastle:bcprov-jdk15on:jar:1.70:runtime
[INFO] |  |        \- org.bouncycastle:bcutil-jdk15on:jar:1.70:runtime
[INFO] |  +- io.opentelemetry:opentelemetry-api:jar:1.34.1:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-context:jar:1.34.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.22.1:compile
[INFO] |  \- org.apache.logging.log4j:log4j-core:jar:2.22.1:compile
[INFO] +- io.vertx:vertx-auth-jwt:jar:5.0.0-SNAPSHOT:compile
[INFO] |  +- io.vertx:vertx-auth-common:jar:5.0.0-SNAPSHOT:compile
[INFO] |  \- io.vertx:vertx-core:jar:5.0.0-SNAPSHOT:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.110.Final:compile
[INFO] |     |  +- io.netty:netty-transport-native-unix-common:jar:4.1.110.Final:compile
[INFO] |     |  \- io.netty:netty-codec:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-handler-proxy:jar:4.1.110.Final:compile
[INFO] |     |  \- io.netty:netty-codec-socks:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-resolver:jar:4.1.110.Final:compile
[INFO] |     +- io.netty:netty-resolver-dns:jar:4.1.110.Final:compile
[INFO] |     |  \- io.netty:netty-codec-dns:jar:4.1.110.Final:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.16.1:compile
[INFO] +- io.vertx:vertx-pg-client:jar:5.0.0-SNAPSHOT:compile
[INFO] |  \- io.vertx:vertx-sql-client:jar:5.0.0-SNAPSHOT:compile
[INFO] \- com.ongres.scram:scram-client:jar:3.0:compile
[INFO]    +- com.ongres.scram:scram-common:jar:3.0:compile
[INFO]    +- com.ongres.stringprep:saslprep:jar:2.1:compile
[INFO]    \- com.ongres.stringprep:stringprep:jar:2.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.949 s
[INFO] Finished at: 2024-06-17T15:50:50+02:00
[INFO] ------------------------------------------------------------------------
```

Notice the `com.ongres` dependencies in particular.

**Comment by wzy1935** [comment]
Yes, I checked and it turns out the reason is that I didn't use the latest `vertx-sql-client` version.

It works now, thank you!
